### ISSUE TITLE
Choose the number of dice. (Defending)

### ISSUE THREAD

**Issue by Cancy0605** [coco1629/RISK356#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by coco1629** [comment]
According to the requirement document, players need to operate in parallel, which means the game should achieve auto-defending strategy.
According to the official rules, the defender can select 1 or 2 dices if they have >= 2 troops. It will select the max num of dice to defend the attacker. If you have better idea, you can modify the strategy. @Cancy0605
